# -*- coding: utf-8 -*-
"""LenNet-5 using keras.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIRWQOpsUkHB1-yTMrQqq3fWvVA2lDV2
"""

from keras.models import Sequential
from keras.layers import Conv2D, AveragePooling2D, Flatten, Dense

# Create model
model = Sequential()

# C1 Layer
model.add(
    Conv2D(
        filters=6,
        kernel_size=5,
        strides=1,
        activation='tanh',
        input_shape=(28, 28, 1),
        padding='same'
    )
)

# S2 Layer
model.add(
    AveragePooling2D(
        pool_size=2,
        strides=2,
        padding='valid'
    )
)

# C3 Layer
model.add(
    Conv2D(
        filters=16,
        kernel_size=5,
        strides=1,
        activation='tanh',
        padding='valid'
    )
)

# S4 Layer
model.add(
    AveragePooling2D(
        pool_size=2,
        strides=2,
        padding='valid'
    )
)

# C5 Layer
model.add(
    Conv2D(
        filters=120,
        kernel_size=5,
        strides=1,
        activation='tanh',
        padding='valid'
    )
)

# Flatten
model.add(Flatten())

# F6 Layer
model.add(
    Dense(
        units=84,
        activation='tanh'
    )
)

# Output Layer
model.add(
    Dense(
        units=10,
        activation='softmax'
    )
)

# Print architecture
model.summary()