# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17quDaqueACpVvRQgH2pDDDrUvY_Z6IOv
"""

import torch
print(torch.__version__)

import torch
print(torch.__version__)