# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2WRavsogmND0majBud9csphzlvWYk8H
"""

from ultralytics import YOLO

model = YOLO("yolov8n.pt")   # pretrained model
results = model("wahid.jpg") # run detection
results.show()

!pip install ultralytics